### ISSUE TITLE
Deal with the use case of multiple ApplicationAuthentication objects in sources with the same auth_id but different app_ids

### ISSUE THREAD

**Issue by katherine-black** [cloudigrade/cloudigrade#669] opened 2021-01-28 23:44 UTC
In GitLab by @werwty on Mar 31, 2020, 10:24

## Summary

Currently when we see a new AuthenticationApplication get created we do a lookup for a clount with a matching arn. 

It could be the case that two AuthenticationApplication objects share the same Authentication (and arn) but different Applications (call it App1 and App2).
When the AuthenticationApplication object is created between the Authentication and App2, we see that there is already an clount with the arn and we do nothing.

- [ ] QE to add automated tests to verify the reproduction steps and expected outcome.

## Steps to Reproduce

```
### Create A Source
SOURCEID=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v1.0/sources \
    name=cloudigrade-appauth-bug source_type_id=2 | jq .id | cut -d\" -f2)
echo $SOURCEID


### Create an Endpoint
ENDPOINTID=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v1.0/endpoints \
    role=aws default=true source_id=$SOURCEID | jq .id | cut -d\" -f2)
echo $ENDPOINTID

### Create an Authentication
AUTHENTICATIONID=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v1.0/authentications \
    authtype=cloud-meter-arn password=arn:aws:iam::114204391493:role/cloudigrade-qa-role resource_type=Endpoint resource_id=$ENDPOINTID | jq .id | cut -d\" -f2)
echo $AUTHENTICATIONID


### Create APP1_ID
APP1_ID=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v1.0/applications \
    application_type_id=5 source_id=$SOURCEID | jq .id | cut -d\" -f2)
echo $APP1_ID

### Create APP2_ID
APP2_ID=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v1.0/applications \
    application_type_id=5 source_id=$SOURCEID | jq .id | cut -d\" -f2)
echo $APP1_ID


### Create a link between App1 and authentication
APPLICATION_AUTHENTICATION_ID_1=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v2.0/application_authentications \
    application_id=$APP1_ID authentication_id=$AUTHENTICATIONID | jq .id | cut -d\" -f2)
echo $APPLICATION_AUTHENTICATION_ID_1


### Create a link between App2 and authentication
APPLICATION_AUTHENTICATION_ID_2=$(http --verify=no --auth $AUTH --body post \
    https://ci.cloud.redhat.com/api/sources/v2.0/application_authentications \
    application_id=$APP2_ID authentication_id=$AUTHENTICATIONID | jq .id | cut -d\" -f2)
echo $APPLICATION_AUTHENTICATION_ID_2

### App1 and App2 should both be marked available but there is not availability status on App2

http --auth $AUTH GET https://ci.cloud.redhat.com/api/sources/v1.0/applications/$APP1_ID
http --auth $AUTH GET https://ci.cloud.redhat.com/api/sources/v1.0/applications/$APP2_ID

```

## Additional context

- **The resolution of this bug must be one of the following.** When a decision is reached, please explain your rationale in comments below.
  1. sources-api fixes this so it's not possible.
  2. sources-api does not fix this, and we agree to ignore it.
  3. sources-api does not fix this, and we implement some kind of handling for it.
- Context for why this is a problem. The following steps would result in us deleting a CloudAccount when we probably should not:
  - first new app_auth leads to us creating a new CloudAccount
  - second new app_auth for same auth is sent to us from sources-api, but we ignore it
  - first app_auth is deleted, and we delete the CloudAccount, but the end user expects the second app_auth to be linked and working.
- If we fix this by storing application_ids as an array, we'll have to be careful not to delete the clount unless there is no other ids in the array.
- The first step to resolving this issue is to have a conversation with other teams to better understand the **intended** use case here, not strictly what is possible via unexpected sources-api interactions. Do we ever expect a real use case for having multiple applications of the same type share the same authentication at **any** time? Consider the possible case of a user creating one SWatch app with name "foo", assigning an ARN auth, realizing they don't like the app name, creating a second SWatch app with name "bar", and assigning the same auth to that second one. Is anything like this reasonable? Consider contacting Adam Grare, Gregg Tanzillo, Richard Vsiansky, and/or Ian Hands both to seek answers and to find the right people who might know the answers.
- We are leaving this issue with `needs definition` until we have those conversations because we expect one of two outcomes: 1) we continue to ignore this because the use case is unsupported and we close this issue as `wontfix`, or 2) we need to define how to refactor things.
- Does this still happen with v3?
  - If not, great! But what's the plan to deprecate v1/v2? Is this getting fixed for v1/v2?
- If this is not being fixed in sources-api, can we reasonably ignore it?
- What are the risks if we simply ignore this scenario?

**Comment by katherine-black** [comment] 2021-01-28 23:44
In GitLab by @infinitewarp on Apr 1, 2020, 10:39

changed title from **Deal with the {-th-}e case of multiple ApplicationAuthentication objects in sources with the same auth_id but different app_ids** to **Deal with the {+us+}e case of multiple ApplicationAuthentication objects in sources with the same auth_id but different app_ids**

**Comment by infinitewarp** [comment] 2021-03-22 15:05
The original reproduction steps are not possible since sources-api changed the relationships around Authentications. You no longer create an Endpoint and reference it when you create an Authentication. Instead the Authentication references the Application directly upon the Authentication's creation.

However, it's still possible to create one Authentication and associate it to two different Applications by creating two different 
ApplicationAuthentications. Despite these multiple associations, the Authentication itself still contains a reference *only* to the Application originally given at its creation. See this demo for example: https://asciinema.org/a/401381

**Comment by infinitewarp** [comment] 2021-03-22 18:33
Asked the sources-api maintainers for feedback here: https://ansible.slack.com/archives/CKJF47RS9/p1616426795003800

**Comment by infinitewarp** [comment] 2021-03-22 20:48
As a result of the conversation in Slack, I'm going to close this issue with no further changes on our end. Per the initial requirements on this issue, we're going with this resolution:
> sources-api fixes this so it's not possible.

From https://ansible.slack.com/archives/CKJF47RS9/p1616439503004400?thread_ts=1616426795.003800&cid=CKJF47RS9

>IMO that is a use-case we don't support, I think this is just the result of sources-api being very open so the applications can do whatever they want with the resources.
>
>I don't think having one authentication tied to multiple applications (in this case one ARN for multiple applications) would make sense. So don't worry about supporting it

**Closed by infinitewarp** 2021-03-22 20:48 UTC
Labels: bug, platform
