### ISSUE TITLE
Celery worker doesn't process scheduled tasks if also configured to listen to a queue.

### ISSUE THREAD

**Issue by ilyavw** [cloudigrade/cloudigrade#291] opened 2018-05-15 13:13 UTC
## Summary

If I have my celery worker configured in such a way that it listens to queues and runs scheduled tasks, it'll fail to run scheduled tasks.

## Steps to Reproduce

1. Run your celery worker with `-l info -A config worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -Q copy_ami_snapshot,create_volume,enqueue_ready_volumes`
2. Register a new account and let it start copying volumes.

## Expected Result

- `scale_up_inspection_cluster()` runs

## Actual Result

- `scale_up_inspection_cluster()` never runs

## Additional context

If you run celery without the -Q params, ie `-l info -A config worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler` the `scale_up_inspection_cluster()` task runs without issue.

**Comment by infinitewarp** [comment] 2018-05-16 01:26
Possibly related anecdote:

When @adberglund and I first started using Celery locally with cloudigrade, we found that Celery's documentation indicates that _by default_ all known queues should be enabled for the `worker` command, and `-Q` should only be necessary if you want to enable specific queues (see [documentation](http://docs.celeryproject.org/en/latest/reference/celery.bin.worker.html#cmdoption-celery-worker-q). However, we could never actually get this to work. Instead, as you see now in our deployment configs, we've had to manually specify _all_ of the task queues we want the worker to care about.

This has bad code smell all over it, but we haven't taken the time to investigate it yet.

There's a good chance we misunderstood something or misconfigured the way we have our tasks mapped to queues. So, whoever picks this bug up should keep that in mind and see if there's anything related to our task configuration that could be affecting this bad behavior with the beat scheduler.

**Comment by noahl** [comment] 2018-05-17 20:33
The bug seems to be that the autoscaling task is routed to the default queue `celery` (because no other queue is explicitly configured), but the `celery` queue is not enabled for the worker, so the messages are never received.

I tested it by standing up a cloudigrade cluster with the current master branch code. The logs included `[2018-05-17 19:12:18,082: INFO/Beat] Scheduler: Sending due task scale_up_inspection_cluster_every_60_min (account.tasks.scale_up_inspection_cluster)`, but nothing else about scaling up.

I also ran `rabbitmqctl list_queues name messages_ready messages_unacknowledged` in the celery container, and got
```rabbitmqctl list_queues name messages_ready messages_unacknowledged
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
copy_ami_snapshot	0	0
celery@cloudigrade-celery-2-5k29s.celery.pidbox	0	0
celery	6	0
celeryev.6967419c-d4cf-4be1-8a75-994f5fc62c3e	0	0
enqueue_ready_volumes	0	0
create_volume	0	0
```

The means that the `celery` queue had 6 messages ready to deliver.

Then I restarted the celery worker, adding `celery` to its queue list. The logs included
```[2018-05-17 20:09:45,015: INFO/MainProcess] Received task: account.tasks.scale_up_inspection_cluster[5544c811-84f0-4940-a575-edf818a9a070]  
[2018-05-17 20:09:45,205: INFO/ForkPoolWorker-4] Starting new HTTPS connection (1): autoscaling.us-east-1.amazonaws.com
[2018-05-17 20:09:45,774: INFO/ForkPoolWorker-5] Not scaling up because no new volumes were found.
[2018-05-17 20:09:45,774: INFO/ForkPoolWorker-5] Task account.tasks.scale_up_inspection_cluster[08c1a503-f264-421e-823b-2c7f6061699f] succeeded in 0.6481769819984038s: None
```

and 5 more copies of the same messages. Also, the output of `rabbitmqctl list_queues name messages_ready messages_unacknowledged` is now
```rabbitmqctl list_queues name messages_ready messages_unacknowledged
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
copy_ami_snapshot	0	0
celery@cloudigrade-celery-1-2k97r.celery.pidbox	0	0
celeryev.d6432fea-ce32-41a2-a43c-af01f241fe6d	0	0
celery	0	0
enqueue_ready_volumes	0	0
create_volume	0	0
ready_volumes	0	0
```

I'll send out a PR.

**Comment by infinitewarp** [comment] 2018-05-18 16:40
Were you able to find any explanation for the "bad code smell" I mentioned in the [previous comment](https://github.com/cloudigrade/cloudigrade/issues/291#issuecomment-389365273) regarding the `-Q` argument, @noahl? It would be nice if we could just drop the long argument list (which the Celery docs imply should work) and not have to remember to append to it every time we define a new task, but I don't know if that's possible for us or maybe a bug on their side.

**Comment by noahl** [comment] 2018-05-21 15:11
@infinitewarp I wasn't able to figure it out, but I'm going to go ahead and run one more test. I just started up a cloudigrade container with no `-Q` argument at all. Let's see what happens!

**Comment by noahl** [comment] 2018-05-21 16:13
@infinitewarp update: removing the `-Q` option made the worker not listen to the queues.

Other than that, I didn't see anything in the documentation about how to make this work. I agree, we shouldn't have to list the queues on the worker command line, and it's a code smell and makes us more brittle. I suggest we make that a separate issue in the backlog.

**Comment by infinitewarp** [comment] 2018-05-21 19:20
@noahl I'm okay with that. Thanks for taking the time to investigate!

**Comment by infinitewarp** [comment] 2018-05-24 14:06
Putting this back in review. Someone _other than_ the person authoring the code needs to verify that the issue is resolved and then close it.

**Comment by abaiken** [comment] 2018-05-29 15:21
I ran ```-l info -A config worker --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -Q copy_ami_snapshot,create_volume,enqueue_ready_volumes``` and registered a new account. The `scale_up_inpsection_cluster` queue then showed messages (so I assume it is running correctly). Any one else should feel free to take a look as I am still learning how everything works!

**Closed by abaiken** 2018-05-29 15:21 UTC
Labels: bug
