### ISSUE TITLE
End-user documentation

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/cloudigrade#108] opened 2018-03-07 20:29 UTC
In order for QE to be effective, we need:

- architectural overview outlining actors, services, APIs, queues
- use case paths defined
- definitions for APIs
- examples of each REST endpoint with:
  - all optional arguments
  - sample inputs (for POSTs)
  - sample outputs

Parts of this are being covered by:
  - https://github.com/cloudigrade/cloudigrade/issues/122
  - https://github.com/cloudigrade/cloudigrade/issues/123

**Comment by kdelee** [comment] 2018-04-12 19:41
Looks like #122 was a dupe of #146 which produced the [architecture doc](https://github.com/cloudigrade/cloudigrade/blob/master/docs/architecture.rst)

Any progress on the API docs? I saw that the automated API doc issue got closed but no information was on the issue as to what was decided.

**Closed** 2021-01-27 19:14 UTC
Labels: needs definition, story
